name: Build M3U Playlist

on:
  schedule:
    # run every 15 minutes
    - cron: "*/15 * * * *"
  workflow_dispatch:  # allow manual run from GitHub UI

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run grabber
        run: python grabber.py

      - name: Commit and push updated files
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add streams.m3u epg.xml
          git commit -m "Auto-update playlist" || echo "No changes to commit"
          git push
