name: LinkGrabber

on:
  schedule:
    # Run every 15 minutes to keep YouTube/Twitch/EXPTV links fresh
    - cron: '*/15 * * * *'

  workflow_dispatch:  # allow manual run
  pull_request:
    branches: [ main ]

jobs:
  runCode:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          pip install -U yt-dlp
          pip install requests lxml pytz beautifulsoup4

      - name: Run grabber
        run: |
          chmod +x exec_grabber.sh
          ./exec_grabber.sh

      - name: Commit and push updated files
        run: |
          git config --global user.email "dp247@hll.localhost"
          git config --global user.name "dp247"
          git add -A
          git commit -m "Playlist updated." || echo "No changes to commit"
          git pull --rebase origin main || true
          git push || true
