name: LinkGrabber

on:
  schedule:
    # Run every 15 minutes to keep YouTube/Twitch/EXPTV links fresh
    - cron: '*/15 * * * *'

  workflow_dispatch:  # allow manual run
  pull_request:
    branches: [ main ]

jobs:
  runCode:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          pip install -U yt-dlp
          pip install requests lxml pytz beautifulsoup4

      - name: Run grabber
        run: |
          git config --global user.email
