name: EXPTV Grabber

on:
  schedule:
    - cron: "*/15 * * * *"   # every 15 minutes
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install deps
        run: |
          python3 -m pip install --upgrade pip
          pip install requests beautifulsoup4

      - name: Run grabber
        run: |
          python3 grabber.py

      - name: Commit & push changes
        run: |
          git config --global user.email "dp247@hll.localhost"
          git config --global user.name "dp247"
          git add -A
          git commit -m "murdercapital.m3u updated with EXPTV" || echo "No changes"
          git pull --rebase origin main || true
          git push || true
